install:
	pip install flake8 mypy [cite: 88]

run:
	python3 a_maze_ing.py config.txt [cite: 89]

lint:
	flake8 .
	mypy --warn-return-any --disallow-untyped-defs a_maze_ing.py [cite: 95, 99]

clean:
	rm -rf __pycache__ .mypy_cache *.txt [cite: 94]